#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const DEFAULT_CONTEXT_WINDOW = 128000;
const DEFAULT_MAX_TOKENS = 32768;
const ZENMUX_MODELS_URL = "https://zenmux.ai/api/v1/models";
const MODELS_DEV_URL = "https://models.dev/api.json";

const projectRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const outputPath = join(projectRoot, "zenmux-models.generated.js");

function toPositiveInt(value, fallback) {
	const num = typeof value === "number" ? value : Number(value);
	if (!Number.isFinite(num) || num <= 0) return fallback;
	return Math.floor(num);
}

function getBasePrice(items) {
	if (!Array.isArray(items) || items.length === 0) return 0;

	const baseline = items.find((item) => {
		if (!item || typeof item !== "object") return false;
		const promptTokens = item.conditions?.prompt_tokens;
		return !item.conditions || (promptTokens?.gte ?? 0) === 0;
	});

	const value = baseline?.value ?? items[0]?.value ?? 0;
	return Number.isFinite(value) ? value : 0;
}

function isAnthropicModel(model) {
	return model.owned_by === "anthropic" || String(model.id || "").startsWith("anthropic/");
}

function resolveModelsDevMaxTokens(model) {
	if (!model || typeof model !== "object") return undefined;

	const candidates = [
		model.limit?.output,
		model.limit?.max_output_tokens,
		model.limit?.max_tokens,
		model.max_output_tokens,
		model.max_tokens,
		model.output_tokens,
	];

	for (const candidate of candidates) {
		const parsed = toPositiveInt(candidate, 0);
		if (parsed > 0) return parsed;
	}

	return undefined;
}

function buildModelsDevMaxTokensMap(modelsDevPayload) {
	const map = new Map();
	if (!modelsDevPayload || typeof modelsDevPayload !== "object") return map;

	for (const providerValue of Object.values(modelsDevPayload)) {
		if (!providerValue || typeof providerValue !== "object") continue;
		const models = providerValue.models;
		if (!models || typeof models !== "object") continue;

		for (const [modelId, modelInfo] of Object.entries(models)) {
			const maxTokens = resolveModelsDevMaxTokens(modelInfo);
			if (!maxTokens) continue;
			map.set(modelId, maxTokens);
		}
	}

	return map;
}

function toProviderModel(rawModel, modelsDevMaxTokens) {
	const id = String(rawModel.id || "").trim();
	if (!id) return null;

	const supportsImage = Array.isArray(rawModel.input_modalities) && rawModel.input_modalities.includes("image");
	const maxTokensFromModelsDev = modelsDevMaxTokens.get(id);

	return {
		id,
		name: String(rawModel.display_name || id),
		api: isAnthropicModel(rawModel) ? "anthropic-messages" : "openai-completions",
		reasoning: Boolean(rawModel.capabilities?.reasoning),
		input: supportsImage ? ["text", "image"] : ["text"],
		cost: {
			input: getBasePrice(rawModel.pricings?.prompt),
			output: getBasePrice(rawModel.pricings?.completion),
			cacheRead: getBasePrice(rawModel.pricings?.input_cache_read),
			cacheWrite: getBasePrice(rawModel.pricings?.input_cache_write_5_min),
		},
		contextWindow: toPositiveInt(rawModel.context_length, DEFAULT_CONTEXT_WINDOW),
		maxTokens: maxTokensFromModelsDev ?? DEFAULT_MAX_TOKENS,
	};
}

async function fetchJson(url) {
	const response = await fetch(url, {
		method: "GET",
		headers: { Accept: "application/json" },
	});

	if (!response.ok) {
		throw new Error(`${url} -> HTTP ${response.status}`);
	}

	return response.json();
}

function serializeGenerated(models) {
	const generatedAt = new Date().toISOString();
	const header = [
		"/**",
		" * GENERATED FILE - DO NOT EDIT.",
		" * Generated by scripts/generate-models.mjs.",
		` * Generated at: ${generatedAt}`,
		` * Source 1: ${ZENMUX_MODELS_URL}`,
		` * Source 2: ${MODELS_DEV_URL}`,
		" */",
		"",
	];

	return `${header.join("\n")}export const ZENMUX_MODELS = ${JSON.stringify(models, null, 2)};\n`;
}

async function main() {
	console.log(`[pi-zenmux] Fetching models from ${ZENMUX_MODELS_URL}`);
	const zenmuxPayload = await fetchJson(ZENMUX_MODELS_URL);
	const zenmuxModels = Array.isArray(zenmuxPayload?.data) ? zenmuxPayload.data : [];
	if (zenmuxModels.length === 0) {
		throw new Error("ZenMux model list is empty");
	}

	console.log(`[pi-zenmux] Fetching maxTokens data from ${MODELS_DEV_URL}`);
	const modelsDevPayload = await fetchJson(MODELS_DEV_URL);
	const modelsDevMaxTokens = buildModelsDevMaxTokensMap(modelsDevPayload);

	const uniqueModels = new Map();
	for (const rawModel of zenmuxModels) {
		const model = toProviderModel(rawModel, modelsDevMaxTokens);
		if (!model) continue;
		uniqueModels.set(model.id, model);
	}

	const models = [...uniqueModels.values()].sort((a, b) => a.id.localeCompare(b.id));
	if (models.length === 0) {
		throw new Error("No valid models generated");
	}

	await writeFile(outputPath, serializeGenerated(models), "utf8");
	console.log(`[pi-zenmux] Wrote ${models.length} models to ${outputPath}`);
}

main().catch((error) => {
	console.error(`[pi-zenmux] Failed to generate models: ${error instanceof Error ? error.message : String(error)}`);
	process.exitCode = 1;
});
